spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery :
        locator :
          enabled : false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 20000
        response-timeout: 20s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s



  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    liveness-state:
    enabled: true
    readiness-state:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints :
  shutdown :
    enabled : true



info:
  app :
    name : "gatewayserver"
    description: "gatewayserver of bank app "
    version : "1.0.0"



logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
