server:
  port: 8071

spring:
  application:
    name: "configServer"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/imad-samadi/Config
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          username: imadsamadi999@gmail.com
          password: Sajidsamadi.12.999.@


encrypt:
  key: "ZNxzTO4Dn1EvjNn695FMIBs2D9untvhs"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
