spring:
  application:
    name: "microTest2"
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    liveness-state:
    enabled: true
    readiness-state:
      enabled: true
eureka :
  instance:
    prefer-ip-address: true
  client :
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

endpoints :
  shutdown :
    enabled : true



