services:
  network-deploy-service:
    networks:
      - BANK

  microservice-base-config:
    extends:
      service: network-deploy-service

    environment:
      SPRING_RABBITMQ_HOST: "rabbit"




  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      configServer:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configServer:8071/
